source "https://rubygems.org"
gem "rails", "4.2.1"
gem "pg"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "figaro"
gem "skylight"
gem "therubyracer"
gem "less-rails"
gem "twitter-bootstrap-rails"
gem "omniauth-github"
gem "faraday"
gem "angularjs-rails"
gem "responders"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "better_errors"
  gem "binding_of_caller"
  gem "rspec-rails"
  gem "capybara"
  gem "pry-rails"
  gem "awesome_print"
  gem "simplecov", :require => false
end
